#!/bin/bash

# exit on the first error
set -e

BCFILE=${1%.*}.bc
OBJFILE=${1%.*}.o
QS_LIB_PATH=`pwd`/lib

qs $1 -m
llvm-link lib/stdlib.bc ${BCFILE} ${@:2} |\
  opt -O3 -std-compile-opts |\
  llc -filetype=obj -o  ${OBJFILE}
gcc ${OBJFILE} `pkg-config libqs --libs` -lgc -lstdc++ -lm -o ${1%.*}
