#!/bin/bash

# exit on the first error
set -e

BCFILE=${1%.*}.bc
EBCFILE=${1%.*}.ebc
OBCFILE=${1%.*}.obc
SFILE=${1%.*}.s
OBJFILE=${1%.*}.o
QS_LIB_PATH=`pwd`/lib

qs $1 -m
llvm-link lib/stdlib.bc ${BCFILE} -o ${EBCFILE} ${@:2}
opt -O3 ${EBCFILE} -o ${OBCFILE}
llc ${OBCFILE} -o ${SFILE}
gcc ${SFILE} -c 
gcc ${OBJFILE} `pkg-config libqs --libs` -lgc -lstdc++ -o ${1%.*}

